### ISSUE TITLE
What about Spanish Sec Talks ?

### ISSUE THREAD

**Issue by insanitus** [PaulSec/awesome-sec-talks#64]
Hi 

  I just found other talks but are in Spanish. The Spanish sec talks are allowed???

Thanks for your time, have a nice day.

**Comment by PaulSec** [comment]
Yes absolutely!
Feel free to add them (and add some kind of flag (eg. "[spanish]") in order to notify the user beforehand. 

Thanks in advance for your contribution 👍

**Comment by alexxn** [comment]
Unfair!
https://github.com/PaulSec/awesome-sec-talks/pull/52
Was closed since it had no translation =)

**Comment by PaulSec** [comment]
I mostly thought it was because you provided only the PDFs to the ZeroNights talk. Feel free to add the videos (but with a comment), thanks @alexxn  :+1:
